/**
 * The corpus is authored once and projected twice — paste-ready markdown for a
 * human to create in Confluence/Jira, and fixture JSON for EIL to ingest. If the
 * two ever drifted the demo's live and offline modes would diverge, so they
 * cannot: both are generated from the single source in ts/corpus/psr.ts, neither
 * is edited by hand, and `pnpm corpus:check` fails in CI the moment the
 * committed tree stops matching what the source projects to.
 *
 *   pnpm corpus:build    write the projections
 *   pnpm corpus:check    fail if the committed tree is stale (for CI / pre-merge)
 */
import { type Dirent, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { CONFLUENCE_SOURCE, JIRA_SOURCE } from "../ts/corpus/psr.js";

export type { ConfluenceFixture, JiraFixture } from "../ts/corpus/psr.js";
import type { ConfluenceFixture, JiraFixture } from "../ts/corpus/psr.js";

export const BANNER = [
  "> **SYNTHETIC DEMO CONTENT.** Illustrative only, generated for a capability",
  "> demonstration. Not a production reference. Do not cite in design or change",
  "> documentation.",
].join("\n");

const withBanner = (body: string) => `${BANNER}\n\n${body.trim()}\n`;

/** Every directory the projection owns entirely — anything else in them is stale. */
const OWNED = ["demo/corpus", "demo/fixtures"];

export function buildCorpus(): { pages: ConfluenceFixture[]; issues: JiraFixture[] } {
  const pages = CONFLUENCE_SOURCE.map((p) => ({ ...p, body: withBanner(p.body) }));
  const issues = JIRA_SOURCE.map((i) => ({
    ...i,
    fields: { ...i.fields, description: withBanner(i.fields.description) },
  }));
  return { pages, issues };
}

/**
 * The paste order matters: the Jira issues the pages reference should exist
 * before anyone reads the pages, and PTR-401's links can only be set once its
 * three related issues are there.
 */
function readme(pages: ConfluenceFixture[], issues: JiraFixture[]): string {
  const restricted = pages.filter((p) => p.acl_groups.length > 0);
  const byKey = new Map(issues.map((i) => [i.key, i]));
  const linked = issues.find((i) => i.key === "PTR-401")!;
  const linkTargets = (linked.fields.issue_links ?? []).map((l) => l.key);
  // Everything except PTR-401 goes in first, so the keys the pages cite resolve.
  const linkedFirst = issues.map((i) => i.key).filter((k) => k !== linked.key);
  // Derived, not asserted: the count of nested pages and the count of distinct
  // parents are different numbers, and a reader creating pages by hand under
  // time pressure is the one who pays for getting either of them wrong.
  const nested = pages.filter((p) => p.ancestors.length > 1);
  const parents = [...new Set(nested.flatMap((p) => p.ancestors.slice(1)))];
  const staleUpdated = pages.find((p) => p.id === "ptrd-2")!.updated.slice(0, 10);
  const row = (key: string) => {
    const i = byKey.get(key)!;
    return `1. **${key}** — ${i.fields.summary} (${i.fields.issuetype}, set status to ${i.fields.status})`;
  };
  const list = (xs: string[]) =>
    xs.length < 2 ? (xs[0] ?? "") : `${xs.slice(0, -1).join(", ")} and ${xs.at(-1)}`;
  // Prose, so counts are spelled — this file is read by a person following it.
  const words = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"];
  const num = (n: number) => words[n] ?? String(n);
  const cap = (s: string) => `${s.slice(0, 1).toUpperCase()}${s.slice(1)}`;
  return [
    "# Paste order — synthetic PTR-DEMO corpus",
    "",
    "GENERATED by `pnpm corpus:build`. Edit `ts/corpus/psr.ts`, not the files here.",
    "",
    "## These pages are visual props, not an ingestion source",
    "",
    "**The demo does not read Confluence or Jira.** It runs entirely off the local",
    "fixture corpus in `demo/fixtures/`, which carries the same text. You are",
    "creating these pages so the audience has something to look at: the presenter",
    "puts a citation on screen and then switches to the browser to show the page it",
    "names.",
    "",
    "That changes what has to be right here:",
    "",
    "- **Ids, ancestors and issue-link wiring no longer have to match anything.** No",
    "  code reads them. They matter only for how the page reads to a human — put a",
    "  page under a sensible parent if it is easy, and do not fight the wiki if it",
    "  is not.",
    ...restricted.flatMap((p) => [
      `- **The \`${p.acl_groups.join(", ")}\` restriction on \`${p.id}\` is cosmetic now.**`,
      "  Nice if your space's permission model makes it a two-click job; skip it",
      "  otherwise. The ACL beat is enforced from the fixture, which carries the group.",
    ]),
    "- **What still matters** is that every page carries its `SYNTHETIC DEMO",
    "  CONTENT` banner, and that the body text matches the fixture. Those are the",
    "  two things that are actually on screen: the banner is what stops anyone",
    "  treating these as a production reference, and the text is what the audience",
    "  compares against the citation.",
    "",
    "Everything in `confluence/` and `jira/` is synthetic and carries that banner.",
    "Create it by hand, in the order below. Bodies are markdown; paste them into the",
    "editor's markdown mode so the banner renders as a quote.",
    "",
    "## 1. Space",
    "",
    `Create the Confluence space **PTR-DEMO**. ${cap(num(nested.length))} of the pages sit under ${num(parents.length)}`,
    `child parents (${list(parents.map((p) => `\`${p}\``))}) — create those as empty parent pages first.`,
    "",
    "## 2. Jira project and the issues the pages reference",
    "",
    `Create Jira project **PTR**, then these ${num(linkedFirst.length)} issues before the pages, so the`,
    "keys the pages cite already resolve:",
    "",
    ...linkedFirst.map(row),
    "",
    "## 3. Confluence pages, in id order",
    "",
    ...pages.map(
      (p) =>
        `1. **${p.id}** — ${p.title}${
          p.ancestors.length > 1 ? ` (under ${p.ancestors.slice(1).join(" / ")})` : ""
        }`,
    ),
    "",
    ...restricted.flatMap((p) => [
      `Restrict **${p.id}** (${p.title}) to \`${p.acl_groups.join(", ")}\` if it is easy —`,
      "a view restriction, not just edit. This is now cosmetic: the ACL beat is",
      `enforced from the fixture, which carries \`acl_groups: ${JSON.stringify(p.acl_groups)}\`.`,
      "It looks tidier if someone clicks through to the page, and nothing breaks if",
      "your space's permission model makes it slow. Skip it rather than lose time.",
      "",
    ]),
    "`ptrd-2` (Gateway Notes) is meant to look stale: set its author to `a.whitfield`",
    `and backdate its last-updated to ${staleUpdated} if the wiki lets you. It does`,
    "not matter if it will not — nothing in the demo depends on the wiki's own",
    "timestamp, only on the dates in the fixtures.",
    "",
    "`ptrd-6` (Credit Service Deployment Runbook) contains a deliberately planted",
    "example AWS key and database URL. The demo quarantines it at ingest from the",
    "fixture copy — that is the point of it, and the page here is what you show",
    "afterwards so the room can see the credential really is sitting in the runbook.",
    "Do not clean it up, and do not paste it anywhere that scans for real",
    "credentials and raises a ticket.",
    "",
    "## 4. The remaining issue and its links",
    "",
    row(linked.key),
    "",
    `Then set ${linked.key}'s links if the project's link types make it quick: relates`,
    `to ${list(linkTargets)}. The fixtures encode the same links independently,`,
    "so the demo's graph edges do not depend on this — it is here so the ticket reads",
    "the same on screen as it does in the artefact. PTR-420 is the open escalation",
    "the demo lands on, so leave it Open with no resolution; that one is worth",
    "getting right, because the presenter shows it.",
    "",
  ].join("\n");
}

/** The whole projection as repo-relative path → exact bytes. */
export function project(): Map<string, string> {
  const { pages, issues } = buildCorpus();
  const out = new Map<string, string>();
  for (const p of pages) {
    out.set(`demo/fixtures/${p.id}.json`, `${JSON.stringify(p, null, 2)}\n`);
    const meta = [
      `_Space PTR-DEMO · parent: ${p.ancestors.join(" / ")}`,
      p.acl_groups.length ? ` · restrict to: ${p.acl_groups.join(", ")}` : "",
      "_",
    ].join("");
    out.set(`demo/corpus/confluence/${p.id}.md`, `# ${p.title}\n\n${meta}\n\n${p.body}`);
  }
  for (const i of issues) {
    out.set(`demo/fixtures/${i.key}.json`, `${JSON.stringify(i, null, 2)}\n`);
    const f = i.fields;
    const meta = `_Project PTR · ${f.issuetype} · ${f.status} · reporter ${f.reporter}_`;
    const comments = f.comments.map((c) => `**Comment — ${c.author}**\n\n${c.body}`).join("\n\n");
    out.set(
      `demo/corpus/jira/${i.key}.md`,
      `${[`# ${i.key} — ${f.summary}`, meta, f.description.trim(), comments].join("\n\n")}\n`,
    );
  }
  out.set("demo/corpus/README.md", `${readme(pages, issues).trimEnd()}\n`);
  return out;
}

export function emit(root = process.cwd()): void {
  for (const [rel, content] of project()) {
    const path = join(root, rel);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, "utf-8");
  }
}

/** Files that exist on disk under the owned directories, repo-relative. */
function committed(root: string, rel: string): string[] {
  let entries: Dirent[];
  try {
    entries = readdirSync(join(root, rel), { withFileTypes: true });
  } catch {
    return [];
  }
  return entries.flatMap((e) =>
    e.isDirectory() ? committed(root, `${rel}/${e.name}`) : [`${rel}/${e.name}`],
  );
}

/**
 * Named, per-file complaints. "The corpus is stale" sends the reader looking
 * through 26 files; "demo/corpus/confluence/ptrd-3.md is STALE" does not.
 */
function stale(root: string): string[] {
  const want = project();
  const problems: string[] = [];
  for (const [rel, content] of want) {
    let actual: string | undefined;
    try {
      actual = readFileSync(join(root, rel), "utf-8");
    } catch {
      problems.push(`${rel} is MISSING`);
      continue;
    }
    if (actual !== content) problems.push(`${rel} is STALE — hand-edited, or its source changed`);
  }
  for (const dir of OWNED) {
    for (const rel of committed(root, dir)) {
      if (!want.has(rel)) problems.push(`${rel} is NOT GENERATED by ts/corpus/psr.ts — delete it`);
    }
  }
  return problems;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const files = project();
  if (process.argv.includes("--check")) {
    const problems = stale(process.cwd());
    if (problems.length > 0) {
      console.error("build-corpus: the committed projection does not match ts/corpus/psr.ts:");
      for (const p of problems) console.error(`  ${p}`);
      console.error("\nRun `pnpm corpus:build` and commit the result. Do not edit demo/ by hand.");
      process.exit(1);
    }
    console.log(`build-corpus: up to date (${files.size} files)`);
  } else {
    emit();
    console.log(`build-corpus: wrote ${files.size} files under demo/`);
  }
}
