/**
 * The corpus is authored once and projected twice — paste-ready markdown for a
 * human to create in Confluence/Jira, and fixture JSON for EIL to ingest. If the
 * two ever drift the demo's live and offline modes diverge, so both are generated
 * from the single source in ts/corpus/psr.ts and neither is edited by hand.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { CONFLUENCE_SOURCE, JIRA_SOURCE } from "../ts/corpus/psr.js";

export type { ConfluenceFixture, JiraFixture } from "../ts/corpus/psr.js";
import type { ConfluenceFixture, JiraFixture } from "../ts/corpus/psr.js";

export const BANNER = [
  "> **SYNTHETIC DEMO CONTENT.** Illustrative only, generated for a capability",
  "> demonstration. Not a production reference. Do not cite in design or change",
  "> documentation.",
].join("\n");

const withBanner = (body: string) => `${BANNER}\n\n${body.trim()}\n`;

export function buildCorpus(): { pages: ConfluenceFixture[]; issues: JiraFixture[] } {
  const pages = CONFLUENCE_SOURCE.map((p) => ({ ...p, body: withBanner(p.body) }));
  const issues = JIRA_SOURCE.map((i) => ({
    ...i,
    fields: { ...i.fields, description: withBanner(i.fields.description) },
  }));
  return { pages, issues };
}

function write(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, "utf-8");
}

/**
 * The paste order matters: the Jira issues the pages reference should exist
 * before anyone reads the pages, and PTR-401's links can only be set once its
 * three related issues are there.
 */
function readme(pages: ConfluenceFixture[], issues: JiraFixture[]): string {
  const restricted = pages.filter((p) => p.acl_groups.length > 0);
  const linkedFirst = ["PTR-388", "PTR-392", "PTR-415", "PTR-420"];
  const byKey = new Map(issues.map((i) => [i.key, i]));
  const staleUpdated = pages.find((p) => p.id === "ptrd-2")!.updated.slice(0, 10);
  const row = (key: string) => {
    const i = byKey.get(key)!;
    return `1. **${key}** — ${i.fields.summary} (${i.fields.issuetype}, set status to ${i.fields.status})`;
  };
  return [
    "# Paste order — synthetic PTR-DEMO corpus",
    "",
    "GENERATED by `pnpm corpus:build`. Edit `ts/corpus/psr.ts`, not the files here.",
    "",
    "Everything in `confluence/` and `jira/` is synthetic and carries a banner",
    "saying so. Create it by hand in the estate you are demoing against, in the",
    "order below. Bodies are markdown; paste them into the editor's markdown mode",
    "so the banner renders as a quote.",
    "",
    "## 1. Space",
    "",
    "Create the Confluence space **PTR-DEMO**. Two pages sit under child parents",
    "(`Compliance`, `Runbooks`) — create those as empty parent pages first.",
    "",
    "## 2. Jira project and the issues the pages reference",
    "",
    "Create Jira project **PTR**, then these four issues before the pages, so the",
    "keys the pages cite already resolve:",
    "",
    ...linkedFirst.map(row),
    "",
    "## 3. Confluence pages, in id order",
    "",
    ...pages.map(
      (p) =>
        `1. **${p.id}** — ${p.title}${
          p.ancestors.length > 1 ? ` (under ${p.ancestors.slice(1).join(" / ")})` : ""
        }`,
    ),
    "",
    ...restricted.map((p) =>
      [
        `Restrict **${p.id}** (${p.title}) to \`${p.acl_groups.join(", ")}\` — a view`,
        "restriction, not just edit. The demo shows an unentitled caller getting no",
        "trace of the page, which only works if the restriction is real.",
      ].join(" "),
    ),
    "",
    "`ptrd-2` (Gateway Notes) is meant to look stale: set its author to `a.whitfield`",
    `and backdate its last-updated to ${staleUpdated} if the wiki lets you. It does`,
    "not matter if it will not — nothing in the demo depends on the wiki's own",
    "timestamp, only on the dates in the fixtures.",
    "",
    "`ptrd-6` (Credit Service Deployment Runbook) contains a deliberately planted",
    "example AWS key and database URL. It is supposed to be quarantined by EIL's",
    "secret scanner on ingest — that is the point of it. Do not clean it up, and do",
    "not paste it anywhere that scans for real credentials and raises a ticket.",
    "",
    "## 4. The remaining issue and its links",
    "",
    ...["PTR-401"].map(row),
    "",
    "Then set PTR-401's links: relates to PTR-392, PTR-415 and PTR-420. PTR-420 is",
    "the open escalation the demo lands on, so leave it Open with no resolution.",
    "",
  ].join("\n");
}

export function emit(root = process.cwd()): void {
  const { pages, issues } = buildCorpus();
  for (const p of pages) {
    write(join(root, "demo/fixtures", `${p.id}.json`), `${JSON.stringify(p, null, 2)}\n`);
    write(
      join(root, "demo/corpus/confluence", `${p.id}.md`),
      `# ${p.title}\n\n_Space PTR-DEMO · parent: ${p.ancestors.join(" / ")}` +
        `${p.acl_groups.length ? ` · restrict to: ${p.acl_groups.join(", ")}` : ""}_\n\n${p.body}`,
    );
  }
  for (const i of issues) {
    write(join(root, "demo/fixtures", `${i.key}.json`), `${JSON.stringify(i, null, 2)}\n`);
    const f = i.fields;
    const meta = `_Project PTR · ${f.issuetype} · ${f.status} · reporter ${f.reporter}_`;
    const comments = f.comments.map((c) => `**Comment — ${c.author}**\n\n${c.body}`).join("\n\n");
    write(
      join(root, "demo/corpus/jira", `${i.key}.md`),
      `${[`# ${i.key} — ${f.summary}`, meta, f.description.trim(), comments].join("\n\n")}\n`,
    );
  }
  write(join(root, "demo/corpus/README.md"), `${readme(pages, issues).trimEnd()}\n`);
}

if (import.meta.url === `file://${process.argv[1]}`) emit();
