/**
 * The canonical body. `.json` is for agents; markdown and HTML are pure
 * projections regenerated from this and therefore cannot drift.
 *
 * Fields marked [G] are generated by the assembler and recomputed by the
 * analyser — disagreement is a gate error, which is what makes the artefact
 * tamper-evident.
 */
import { z } from "zod";

export const Fib = z.union([
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(5),
  z.literal(8),
  z.literal(13),
  z.literal(21),
]);

export const DECISIONS = ["leaf", "decompose", "clarify"] as const;
export const RESOLVED_FROM = [
  "context",
  "architecture",
  "project_docs",
  "knowledge_base",
  "human",
] as const;
export const SEVERITIES = ["error", "warning"] as const;

export const Finding = z.object({
  id: z.string(),
  severity: z.enum(SEVERITIES),
  path: z.string(),
  message: z.string(),
});
export type Finding = z.infer<typeof Finding>;

export const Grounding = z.object({
  source: z.string(),
  /** an EIL document id — "confluence:page:ptrd-2" — the seam into the knowledge plane */
  docId: z.string().min(1),
  title: z.string(),
  url: z.string().nullish(),
  /** must appear verbatim in the cited document; CLARIFY-005 enforces it */
  quote: z.string().min(1),
  retrievedAt: z.string(),
  traceId: z.string().nullish(),
  hedged: z.boolean().default(false), // [G]
});

export const AcceptanceCriterion = z.object({
  id: z.string().regex(/^AC-\d+$/),
  stakeholder: z.string().min(1),
  given: z.string().min(1),
  when: z.string().min(1),
  // biome-ignore lint/suspicious/noThenProperty: Gherkin given/when/then field, required verbatim
  then: z.array(z.string().min(1)).min(1),
  observable: z.boolean().default(false), // [G]
});

export const ScorePass = z.object({
  unknowns: Fib,
  complexity: Fib,
  /** [G] — deliberately accepts a WRONG band so SCORE-001 owns the verdict */
  magnitude: Fib,
  decision: z.enum(DECISIONS),
  at: z.string(),
  note: z.string().optional(),
});

export interface RequirementNodeT {
  id: string;
  parentId?: string | undefined;
  nodeKey: string;
  statement: string;
  score: z.infer<typeof ScorePass>;
  scoreHistory: z.infer<typeof ScorePass>[];
  decision: (typeof DECISIONS)[number];
  isLeaf: boolean;
  children?: RequirementNodeT[] | undefined;
  acceptanceCriteria?: z.infer<typeof AcceptanceCriterion>[] | undefined;
  grounding: z.infer<typeof Grounding>[];
  resolvedFrom?: (typeof RESOLVED_FROM)[number] | undefined;
  residualRef?: string | undefined;
}

export const RequirementNode: z.ZodType<RequirementNodeT, z.ZodTypeDef, unknown> = z.lazy(() =>
  z.object({
    /** every child id extends its parent's: REQ-ROOT.1.2 */
    id: z.string().regex(/^REQ-ROOT(\.\d+)*$/),
    /** absent on the root — structural fields are absent, never empty */
    parentId: z.string().optional(),
    nodeKey: z.string().regex(/^[a-z0-9]+(?:[-.][a-z0-9]+)*$/),
    statement: z.string().min(1),
    score: ScorePass,
    scoreHistory: z.array(ScorePass).min(1),
    decision: z.enum(DECISIONS),
    isLeaf: z.boolean(), // [G]
    children: z.array(RequirementNode).optional(),
    acceptanceCriteria: z.array(AcceptanceCriterion).optional(),
    grounding: z.array(Grounding).default([]),
    resolvedFrom: z.enum(RESOLVED_FROM).optional(),
    residualRef: z.string().optional(),
  }),
);

export const Clarification = z.object({
  id: z.string().regex(/^CL-\d+$/),
  nodeId: z.string(),
  question: z.string().min(1),
  options: z
    .array(
      z.object({
        id: z.string().regex(/^OPT-\d+$/),
        text: z.string().min(1),
        implication: z.string().min(1),
      }),
    )
    .default([]),
  answer: z
    .object({ chosenOptionId: z.string().optional(), freetext: z.string().optional() })
    .optional(),
  answeredBy: z
    .object({ kind: z.enum(["human", "knowledge_base"]), name: z.string().min(1) })
    .optional(),
  answeredAt: z.string().optional(),
  resultingDetail: z.string().optional(),
  resolvedFrom: z.enum(RESOLVED_FROM).optional(),
  grounding: z.array(Grounding).default([]),
});

export const Residual = z.object({
  id: z.string().regex(/^RU-\d+$/),
  kind: z.enum(["ResidualUncertainty", "ResidualRisk", "accepted_complexity"]),
  nodeId: z.string(),
  statement: z.string().min(1),
  mitigation: z.string().optional(),
  /** a residual is only carried on a named human's authority */
  acceptedBy: z.object({ kind: z.literal("human"), name: z.string().min(1) }),
  acceptedAt: z.string(),
});

export const Signoff = z.object({
  approvers: z
    .array(
      z.object({
        name: z.string().min(1),
        role: z.string(),
        /** deliberately loose — GATE-006 owns "must be human" */
        kind: z.string(),
        at: z.string(),
      }),
    )
    .default([]),
  /** deliberately loose — GATE-001 owns "passed is never admissible" */
  result: z.string(),
});

export const ReqsBody = z.object({
  schemaVersion: z.literal("1.0"),
  metadata: z.object({
    workItem: z.string().min(1),
    title: z.string().min(1),
    deliveryType: z.object({
      kind: z.enum(["ui", "backend", "migration", "mixed"]),
      tech: z.enum(["new", "legacy"]),
    }),
    createdAt: z.string(),
    /** the staleness pin downstream phases record and compare */
    updatedAt: z.string(),
    executionProfile: z.object({ mode: z.enum(["full", "fast"]) }).default({ mode: "full" }),
    generator: z.object({
      agent: z.string(),
      model: z.string().nullish(),
      version: z.string(),
    }),
    /** stamped so no run can be misrepresented as the other */
    corpusMode: z.enum(["fixtures", "live"]),
  }),
  tree: RequirementNode,
  clarifications: z.array(Clarification).default([]),
  residuals: z.array(Residual).default([]),
  /** [G] AC id -> node id */
  traceability: z.record(z.string(), z.string()).default({}),
  /** [G] */
  coverage: z
    .object({
      leaves: z.number(),
      acs: z.number(),
      unknownsTotal: z.number(),
      grounded: z.number(),
      escalated: z.number(),
      carried: z.number(),
    })
    .optional(),
  signoff: Signoff.optional(),
  /** written by the analyser, never by the model */
  analysis: z
    .object({ ranAt: z.string(), checksRun: z.number(), findings: z.array(Finding) })
    .optional(),
});
export type ReqsBody = z.infer<typeof ReqsBody>;

export function parseReqs(
  raw: unknown,
): { ok: true; body: ReqsBody } | { ok: false; issues: string[] } {
  const r = ReqsBody.safeParse(raw);
  if (r.success) return { ok: true, body: r.data };
  return {
    ok: false,
    issues: r.error.issues.map((i) => `${i.path.join(".") || "(root)"}: ${i.message}`),
  };
}

/** Depth-first walk, parents before children, with depth starting at 1. */
export function* walk(
  node: RequirementNodeT,
  depth = 1,
): Generator<{ node: RequirementNodeT; depth: number; path: string }> {
  yield { node, depth, path: node.id };
  for (const c of node.children ?? []) yield* walk(c, depth + 1);
}
